CREATE TABLE scrape_runs (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    spider_name VARCHAR(255) NOT NULL,
    started_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    finished_at DATETIME(6),
    status ENUM('running', 'succeeded', 'failed') NOT NULL,
    items_seen INT NOT NULL DEFAULT 0,
    items_inserted INT NOT NULL DEFAULT 0,
    items_changed INT NOT NULL DEFAULT 0,
    error_message TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE listings (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    source VARCHAR(100) NOT NULL DEFAULT 'pakwheels',
    source_listing_id VARCHAR(255) NOT NULL,
    url TEXT NOT NULL,
    name TEXT,
    price_pkr BIGINT,
    make VARCHAR(255),
    model VARCHAR(255),
    model_year SMALLINT,
    location VARCHAR(255),
    mileage_km INT,
    registered_city VARCHAR(255),
    engine_type VARCHAR(100),
    engine_capacity_cc INT,
    transmission VARCHAR(100),
    color VARCHAR(100),
    assembly VARCHAR(100),
    body_type VARCHAR(100),
    features JSON NOT NULL,
    source_updated_at DATE,
    first_seen_at DATETIME(6) NOT NULL,
    last_seen_at DATETIME(6) NOT NULL,
    last_seen_run_id BIGINT UNSIGNED,
    content_hash CHAR(64) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    inactive_at DATETIME(6),
    CONSTRAINT listings_source_listing_id_not_blank CHECK (TRIM(source_listing_id) <> ''),
    CONSTRAINT listings_url_not_blank CHECK (TRIM(url) <> ''),
    CONSTRAINT listings_source_source_listing_id_key UNIQUE (source, source_listing_id),
    CONSTRAINT listings_last_seen_run_fk FOREIGN KEY (last_seen_run_id) REFERENCES scrape_runs(id),
    INDEX listings_price_pkr_idx (price_pkr),
    INDEX listings_make_model_model_year_idx (make, model, model_year),
    INDEX listings_last_seen_at_idx (last_seen_at),
    INDEX listings_active_idx (source, is_active, last_seen_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE listing_versions (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    listing_id BIGINT UNSIGNED NOT NULL,
    scrape_run_id BIGINT UNSIGNED NOT NULL,
    observed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    url TEXT NOT NULL,
    name TEXT,
    price_pkr BIGINT,
    make VARCHAR(255),
    model VARCHAR(255),
    model_year SMALLINT,
    location VARCHAR(255),
    mileage_km INT,
    registered_city VARCHAR(255),
    engine_type VARCHAR(100),
    engine_capacity_cc INT,
    transmission VARCHAR(100),
    color VARCHAR(100),
    assembly VARCHAR(100),
    body_type VARCHAR(100),
    features JSON NOT NULL,
    source_updated_at DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    inactive_at DATETIME(6),
    content_hash CHAR(64) NOT NULL,
    changed_fields JSON NOT NULL,
    CONSTRAINT listing_versions_listing_fk FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
    CONSTRAINT listing_versions_run_fk FOREIGN KEY (scrape_run_id) REFERENCES scrape_runs(id),
    CONSTRAINT listing_versions_listing_id_content_hash_key UNIQUE (listing_id, content_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE price_history (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    listing_id BIGINT UNSIGNED NOT NULL,
    scrape_run_id BIGINT UNSIGNED NOT NULL,
    observed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    old_price_pkr BIGINT,
    new_price_pkr BIGINT,
    CONSTRAINT price_history_listing_fk FOREIGN KEY (listing_id) REFERENCES listings(id) ON DELETE CASCADE,
    CONSTRAINT price_history_run_fk FOREIGN KEY (scrape_run_id) REFERENCES scrape_runs(id),
    CONSTRAINT price_history_price_changed CHECK (NOT (old_price_pkr <=> new_price_pkr)),
    INDEX price_history_listing_id_observed_at_idx (listing_id, observed_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
